# Generated by Django 5.1 on 2024-08-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='observaciones',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
