# Generated by Django 5.1 on 2024-08-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_paciente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, default='57', max_length=12, null=True),
        ),
    ]
